"""
Moltemplate backend for bead-spring models.

Emits .lt files mirroring AutoPoly's atomistic pipeline conventions
(monomer .lt objects, per-chain polymer .lt objects with explicit
coordinates and "Data Bond List"/"Data Angles" sections, and a system.lt),
then optionally runs the bundled moltemplate to produce system.data +
system.in.init/settings.

Layout produced under ``<path>/moltemplate/``::

    bead_spring.lt      CG force field: masses, styles, pair/bond/angle coeffs
    bead_<Type>.lt      one single-bead monomer object per bead type
    chains.lt           one object per chain: beads at generated coordinates
                        + explicit bond list + typed angle list
    system.lt           instantiates every chain + Data Boundary
    in.polymer          LAMMPS driver (includes system.in.init/settings)

Because coordinates are generated by the Python SAW/MC machinery before
.lt emission, arbitrary architectures (stars, combs, rings, mixtures)
work uniformly: the graph edge list becomes "Data Bond List" entries and
graph angle triplets become "Data Angles" entries with per-triplet
``@angle:`` types (branch angles fully configurable).
"""

import subprocess
from pathlib import Path
from typing import Callable, Dict, List, Optional, Tuple

import numpy as np

from ..core.logger import setup_logger
from ..core.exceptions import WorkflowError
from .architectures import BeadArchitecture
from .bead_spring import AngleType, BeadType

logger = setup_logger()


def _moltemplate_scripts_dir() -> Path:
    """Path to the bundled moltemplate scripts directory."""
    return Path(__file__).resolve().parent.parent / "extern" / "moltemplate" / "scripts"


def write_bead_spring_lt(
    filepath: Path,
    bead_types: List[BeadType],
    pair_coeffs: Dict[Tuple[int, int], Tuple[float, float]],
    bond_style: str,
    k_bond: float,
    bond_length: float,
    fene_r0: float,
    pair_style: str,
    use_angles: bool,
    angle_type_map: Dict[Tuple[str, str, str], int],
    resolve_angle_params: Callable[[Tuple[str, str, str]], Tuple[float, float]],
) -> None:
    """
    Write bead_spring.lt: the coarse-grained force-field object.

    Atom types are named ``@atom:<bead_name>``; the single bond type is
    ``@bond:bs1``; angle types are ``@angle:at<id>`` per canonical triplet.
    """
    max_sigma = max(bt.sigma for bt in bead_types)
    if pair_style == "wca":
        cutoff = (2 ** (1 / 6)) * max_sigma
    else:
        cutoff = 2.5 * max_sigma

    with open(filepath, "w") as f:
        f.write("# Coarse-grained bead-spring force field\n")
        f.write("# Auto-generated by AutoPoly\n\n")
        f.write("BeadSpringFF {\n\n")

        # Atom type names
        f.write("  # Atom type definitions\n")
        for bt in bead_types:
            f.write(f"  # @atom:{bt.name}  mass={bt.mass}\n")
        f.write("\n")

        # Masses
        f.write('  write_once("Data Masses") {\n')
        for bt in bead_types:
            f.write(f"    @atom:{bt.name} {bt.mass:.3f}\n")
        f.write("  }\n\n")

        # Init: units, atom_style, styles
        f.write('  write_once("In Init") {\n')
        f.write("    units lj\n")
        f.write("    atom_style full\n")
        f.write(f"    pair_style lj/cut {cutoff:.5f}\n")
        if bond_style == "fene":
            f.write("    bond_style fene\n")
            f.write("    special_bonds fene\n")
        else:
            f.write("    bond_style harmonic\n")
        if use_angles:
            f.write("    angle_style harmonic\n")
        f.write("  }\n\n")

        # Settings: coeffs
        f.write('  write_once("In Settings") {\n')
        for (i, j), (eps, sig) in sorted(pair_coeffs.items()):
            name_i = bead_types[i - 1].name
            name_j = bead_types[j - 1].name
            f.write(
                f"    pair_coeff @atom:{name_i} @atom:{name_j} "
                f"{eps:.4f} {sig:.4f}\n"
            )
        if pair_style == "wca":
            f.write("    pair_modify shift yes\n")

        if bond_style == "fene":
            eps = bead_types[0].epsilon
            sig = bead_types[0].sigma
            f.write(
                f"    bond_coeff @bond:bs1 {k_bond:.1f} {fene_r0:.4f} "
                f"{eps:.4f} {sig:.4f}\n"
            )
        else:
            f.write(f"    bond_coeff @bond:bs1 {k_bond:.1f} {bond_length:.4f}\n")

        if use_angles:
            for triplet, type_id in sorted(
                angle_type_map.items(), key=lambda x: x[1]
            ):
                k, theta0 = resolve_angle_params(triplet)
                triplet_str = "-".join(triplet)
                f.write(
                    f"    angle_coeff @angle:at{type_id} {k:.4f} "
                    f"{theta0:.1f}  # {triplet_str}\n"
                )
        f.write("  }\n")
        f.write("}\n")


def write_bead_lt(filepath: Path, bead_type: BeadType) -> None:
    """Write one single-bead monomer object for a bead type."""
    with open(filepath, "w") as f:
        f.write(f'import "bead_spring.lt"\n')
        f.write(f"bead_{bead_type.name} inherits BeadSpringFF {{\n")
        f.write('  write("Data Atoms") {\n')
        f.write(
            f"    $atom:b $mol:... @atom:{bead_type.name} 0.0 0.0 0.0 0.0\n"
        )
        f.write("  }\n")
        f.write(f"}}  # bead_{bead_type.name}\n")


def write_chains_lt(
    filepath: Path,
    chain_architectures: List[BeadArchitecture],
    positions: List[np.ndarray],
    chain_indices: List[Tuple[int, int]],
    use_angles: bool,
    angle_type_map: Dict[Tuple[str, str, str], int],
    include_branch_angles: bool,
    canonical_triplet: Callable[[str, str, str], Tuple[str, str, str]],
) -> None:
    """
    Write chains.lt: one moltemplate object per chain with beads at their
    generated coordinates, explicit "Data Bond List" entries from the
    graph edge list, and typed "Data Angles" entries from graph triplets.
    """
    with open(filepath, "w") as f:
        f.write('import "bead_spring.lt"\n')
        seen_imports = set()
        for arch in chain_architectures:
            for bt_name in arch.bead_types:
                if bt_name not in seen_imports:
                    f.write(f'import "bead_{bt_name}.lt"\n')
                    seen_imports.add(bt_name)
        f.write("\n")

        for chain_idx, (arch, (start, end)) in enumerate(
            zip(chain_architectures, chain_indices)
        ):
            obj = f"chain_{chain_idx + 1}"
            f.write(f"{obj} inherits BeadSpringFF {{\n")
            f.write("  create_var {$mol}\n\n")

            # Bead instances at generated coordinates
            for local_bead, global_idx in enumerate(range(start, end)):
                pos = positions[global_idx]
                bt_name = arch.bead_types[local_bead]
                f.write(
                    f"  bead[{local_bead}] = new bead_{bt_name}"
                    f".move({pos[0]:.4f},{pos[1]:.4f},{pos[2]:.4f})\n"
                )
            f.write("\n")

            # Bonds (all share the single @bond:bs1 type)
            f.write('  write("Data Bonds") {\n')
            for bond_idx, (i, j) in enumerate(arch.bonds):
                f.write(
                    f"    $bond:b{bond_idx + 1} @bond:bs1 "
                    f"$atom:bead[{i}]/b $atom:bead[{j}]/b\n"
                )
            f.write("  }\n")

            # Angles with per-triplet @angle types (branch-aware)
            if use_angles:
                triplets = arch.angle_triplets(include_branch=include_branch_angles)
                if triplets:
                    f.write("\n")
                    f.write('  write("Data Angles") {\n')
                    for angle_idx, (i, j, k) in enumerate(triplets):
                        triplet = canonical_triplet(
                            arch.bead_types[i],
                            arch.bead_types[j],
                            arch.bead_types[k],
                        )
                        type_id = angle_type_map[triplet]
                        f.write(
                            f"    $angle:a{angle_idx + 1} @angle:at{type_id} "
                            f"$atom:bead[{i}]/b $atom:bead[{j}]/b "
                            f"$atom:bead[{k}]/b\n"
                        )
                    f.write("  }\n")
            f.write(f"}}  # {obj} ({arch.name})\n\n")


def write_system_lt(
    filepath: Path,
    n_chains: int,
    box_size: float,
    bead_type_names: List[str],
) -> None:
    """Write system.lt: imports, one instance per chain, Data Boundary."""
    with open(filepath, "w") as f:
        f.write('import "bead_spring.lt"\n')
        for bt_name in bead_type_names:
            f.write(f'import "bead_{bt_name}.lt"\n')
        f.write('import "chains.lt"\n\n')
        for chain_idx in range(n_chains):
            f.write(f"chains[{chain_idx}] = new chain_{chain_idx + 1}\n")
        f.write("\n")
        f.write('write_once("Data Boundary") {\n')
        f.write(f"   {-box_size / 2:.4f}  {box_size / 2:.4f}  xlo xhi\n")
        f.write(f"   {-box_size / 2:.4f}  {box_size / 2:.4f}  ylo yhi\n")
        f.write(f"   {-box_size / 2:.4f}  {box_size / 2:.4f}  zlo zhi\n")
        f.write("}\n")


def write_moltemplate_input_script(filepath: Path) -> None:
    """
    Write in.polymer for the moltemplate backend.

    Styles come from system.in.init and coeffs from system.in.settings
    (both generated by moltemplate from bead_spring.lt).
    """
    with open(filepath, "w") as f:
        f.write("# LAMMPS input script for bead-spring polymer (moltemplate backend)\n")
        f.write("# Auto-generated by AutoPoly\n\n")

        f.write("boundary        p p p\n\n")

        f.write("read_data       system.data\n")
        f.write("include         system.in.init\n")
        f.write("include         system.in.settings\n\n")

        # Larger skin (2.0) for FENE to prevent lost atoms
        f.write("neighbor        2.0 bin\n")
        f.write("neigh_modify    every 2 delay 4 check yes\n\n")

        f.write("thermo_style    custom step temp pe ke etotal press vol density\n")
        f.write("thermo          1000\n\n")

        f.write("dump            1 all custom 1000 dump.lammpstrj id type mol x y z\n")
        f.write("dump_modify     1 sort id\n\n")

        f.write("# Energy minimization\n")
        f.write("minimize        1.0e-4 1.0e-6 1000 10000\n")
        f.write("write_restart   min.restart\n")
        f.write("write_data      min.data\n")
        f.write("reset_timestep  0\n\n")

        f.write("# Production MD\n")
        f.write("timestep        0.001\n")
        f.write("fix             1 all nvt temp 1.0 1.0 0.1 tchain 3\n")
        f.write("run             100000\n")
        f.write("write_restart   prod.restart\n")
        f.write("write_data      prod.data\n")


def generate_moltemplate_files(
    path: str,
    bead_types: List[BeadType],
    chain_architectures: List[BeadArchitecture],
    positions: List[np.ndarray],
    chain_indices: List[Tuple[int, int]],
    box_size: float,
    pair_coeffs: Dict[Tuple[int, int], Tuple[float, float]],
    bond_style: str,
    k_bond: float,
    bond_length: float,
    fene_r0: float,
    pair_style: str,
    use_angles: bool,
    angle_type_map: Dict[Tuple[str, str, str], int],
    resolve_angle_params: Callable[[Tuple[str, str, str]], Tuple[float, float]],
    include_branch_angles: bool,
    canonical_triplet: Callable[[str, str, str], Tuple[str, str, str]],
    run_moltemplate: bool = True,
) -> Path:
    """
    Generate all moltemplate .lt files for a bead-spring system and
    optionally run moltemplate.

    All structural information comes from the per-chain architectures
    (graph edge lists and angle triplets) and the generated coordinates,
    so arbitrary architectures and mixtures are supported uniformly.

    Args:
        path: Project directory; files go under ``<path>/moltemplate/``.
        bead_types: Shared bead type table.
        chain_architectures: One BeadArchitecture per chain.
        positions: Flat position list (global indexing).
        chain_indices: (start, end) per chain into ``positions``.
        box_size: Cubic box side length.
        pair_coeffs: Mixed pair coefficients (1-based type ids).
        bond_style, k_bond, bond_length, fene_r0, pair_style: Potentials.
        use_angles: Whether angles are included.
        angle_type_map: Canonical triplet -> angle type id.
        resolve_angle_params: triplet -> (k, theta0).
        include_branch_angles: Whether branch triplets are included.
        canonical_triplet: (t1, t2, t3) -> canonical triplet.
        run_moltemplate: Run the bundled moltemplate after writing files.

    Returns:
        Path to the moltemplate directory.

    Raises:
        WorkflowError: If moltemplate fails.
    """
    moltemplate_dir = Path(path) / "moltemplate"
    if moltemplate_dir.exists():
        import shutil
        shutil.rmtree(moltemplate_dir)
    moltemplate_dir.mkdir(parents=True, exist_ok=True)

    write_bead_spring_lt(
        moltemplate_dir / "bead_spring.lt",
        bead_types, pair_coeffs, bond_style, k_bond, bond_length, fene_r0,
        pair_style, use_angles, angle_type_map, resolve_angle_params,
    )
    for bt in bead_types:
        write_bead_lt(moltemplate_dir / f"bead_{bt.name}.lt", bt)
    write_chains_lt(
        moltemplate_dir / "chains.lt",
        chain_architectures, positions, chain_indices,
        use_angles, angle_type_map, include_branch_angles, canonical_triplet,
    )
    write_system_lt(
        moltemplate_dir / "system.lt",
        len(chain_architectures), box_size,
        [bt.name for bt in bead_types],
    )
    write_moltemplate_input_script(moltemplate_dir / "in.polymer")

    if run_moltemplate:
        moltemplate_sh = _moltemplate_scripts_dir() / "moltemplate.sh"
        process = subprocess.run(
            ["bash", str(moltemplate_sh), "-nocheck", "./system.lt"],
            cwd=moltemplate_dir,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        if process.returncode != 0:
            logger.error("Moltemplate execution failed:")
            logger.error(process.stderr)
            stdout_lines = process.stdout.splitlines()
            if stdout_lines:
                logger.error("Last output lines:")
                for line in stdout_lines[-5:]:
                    logger.error(line)
            raise WorkflowError("Moltemplate execution failed")

        for required in ("system.data", "system.in.settings", "system.in.init"):
            if not (moltemplate_dir / required).exists():
                raise WorkflowError(
                    f"Moltemplate did not generate {required} in {moltemplate_dir}"
                )
        logger.info(f"Moltemplate output generated in {moltemplate_dir}")

    return moltemplate_dir
